### ISSUE TITLE
Violation of the Developer ToS

### ISSUE THREAD

**Issue by Variiuz** [ProjectBorealis/DiscordGameSDK#3]
You guys should get the user to download those discord files themselves, it's a violation of Discord ToS to include the libs.

**Comment by mastercoms** [comment]
Our current interpretation is that we may, and unless there's word from the copyright holders themselves (Discord), I'm not sure if we need to change anything without further information.

> 1. API AND SDK
1.1 API and SDK. The API and SDK consists of specific programmatic application programming interfaces, interface definitions, **generated code libraries** and associated tools. The API is an interface that facilitates interaction with the Platform’s servers. The SDK is software code that is designed to be integrated into and to ship bundle with your applications (“Applications”).
1.2 API or SDK Modifications. Discord reserves the right to modify the API or SDK, and to release subsequent versions. You may be required to use the most recent version of the API or SDK in order to obtain certain functionality.
1.3 Support. Discord has no obligation to provide you or any users of your Applications with support, software upgrades, enhancements or modifications to the API or SDK. If Discord makes available updated versions of the API or SDK, you will use reasonable efforts to use only the then-current version as soon as possible and will use only the then-current version within 30 days of the date the then-current version becomes available. You understand and agree that you are solely responsible for providing user support and any other technical assistance for your Applications and other products and/or services.
> 2. LICENSE, ACCOUNTS AND RESTRICTIONS
2.1 API or SDK License. Subject to the terms and conditions of this Agreement, Discord grants you a limited, non-exclusive, revocable, non-transferable license to access and **use the API or SDK solely to as necessary to (i) develop, test, display and execute your Applications with the API or SDK functionality included; and (ii) distribute to third parties, or permit third parties to access, the API or SDK as integrated into your Applications.**
2.2 Restrictions. You shall not, and shall not permit any person, directly or indirectly, to (i) reverse engineer, disassemble, reconstruct, decompile, translate, modify or copy the API or SDK, other than as explicitly permitted hereunder (except to the extent the foregoing restriction is expressly prohibited by applicable law notwithstanding this limitation), (ii) create derivative works of the API or SDK or any aspect or portion thereof, including without limitation, source code and algorithms, (iii) distribute or otherwise disseminate the API or SDK by any means or in any form, **except as an integral part of your Applications;** (iv) use the API or SDK in connection with any Applications that include any malware or other harmful code or that facilitate spamming in any way; (v) circumvent any limits or any privacy or access controls (or attempt to do so); or (vi) include any advertisements or other promotions within the functionality enabled by the API or SDK. Except as expressly set forth in this Agreement, Discord reserves all rights in or the API and SDK.

https://discordapp.com/developers/docs/legal
